### ISSUE TITLE
Can not integrate exprssionoasis 3.2 lib in my application

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mohitkgupta/expressionoasis#13]
```
What steps will reproduce the problem?
1. I add the library to my local repository.
2. by executin first line I get Error
ExpressionContext expressionContext = new ExpressionContext();

testXYZ(org.ird.raven.vault.odk.XYZTestCase)Time elapsed: 4.659 sec  <<< ERROR! 
java.lang.NoClassDefFoundError: org/simpleframework/xml/Serializer
at 
org.vedantatree.expressionoasis.ExpressionContext.registerFunctionProviders(Expr
essionContext.java:113)
at 
org.vedantatree.expressionoasis.ExpressionContext.<init>(ExpressionContext.java:
95)
.
.
.
Caused by: java.lang.ClassNotFoundException: org.simpleframework.xml.Serializer
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 52 more


In readme.txt file it is mentioned that "There is a dependency which points to 
a custom library, Utilities-1.1.jar", but I didn't find the library in 
downloaded library folder.

What is the expected output? What do you see instead?


What version of the product are you using? On what operating system?
exprssionoasis 3.2 on windows 8

Please provide any additional information below.

```

Original issue reported on code.google.com by `hameedul...@gmail.com` on 23 Mar 2015 at 10:25

**Comment by mohitkgupta** [comment]
Thanks for adding the details. 

To add, build system is updated to gradle with 3.2. You may get more instructions in readme and build.gradle file. Let us know for any issue. Thanks.
